# Generated by Django 3.1.3 on 2020-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=12, verbose_name='实体类别')),
            ],
            options={
                'verbose_name': '实体类别',
                'verbose_name_plural': '实体类别',
                'db_table': 'qestionsys_entitytype',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=12, verbose_name='关系类别')),
            ],
            options={
                'verbose_name': '关系类别',
                'verbose_name_plural': '关系类别',
                'db_table': 'qestionsys_relationtype',
            },
        ),
    ]
