# Generated by Django 2.1.5 on 2020-10-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='笔记id')),
                ('title', models.CharField(max_length=12, verbose_name='笔记标题')),
                ('content', models.TextField(verbose_name='笔记内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'db_table': 'qestionsys_note',
            },
        ),
    ]
