# Generated by Django 2.1.5 on 2020-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201025_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.IntegerField(max_length=128, primary_key=True, serialize=False, verbose_name='笔记id'),
        ),
    ]
