# Generated by Django 2.1.5 on 2020-10-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20201025_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=255, verbose_name='笔记内容'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
