# Generated by Django 3.1.3 on 2020-11-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201105_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=12, verbose_name='笔记标题')),
                ('answer', models.TextField(max_length=255, verbose_name='笔记内容')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'qestionsys_quest',
            },
        ),
    ]
