# Generated by Django 3.1.3 on 2020-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='question',
            field=models.TextField(max_length=255, verbose_name='笔记标题'),
        ),
    ]
